### ISSUE TITLE
Issue with nav bar responsiveness

### ISSUE THREAD

**Issue by Connor812** [Connor812/Project-1#26]
Nav bar isn't responsive, It is done when there are no issues when shrinking the page.

**Comment by navaulakh24** [comment]
Using Boostrap nav bar feature, I am not getting the responsiveness needed for smaller screen sizes. I have added "-sm" in the navbar class and still an issue. Will have to figure out if it is the wrong Bootstrap layout to use, or fix it using css styling in the stylesheet which will be more work.

**Comment by navaulakh24** [comment]
Using Boostrap nav bar feature, I am not getting the responsiveness needed for smaller screen sizes. I have added "-sm" in the navbar class and still an issue. Will have to figure out if it is the wrong Bootstrap layout to use, or fix it using css styling in the stylesheet which will be more work.
